version: '3'

volumes:
  db-data: {}

services:
  db:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    env_file: .env
    stdin_open: true
    tty: true
